"""some updates

Revision ID: 150281b956b0
Revises: f9328d67702b
Create Date: 2026-01-15 11:14:45.916902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150281b956b0'
down_revision: Union[str, Sequence[str], None] = 'f9328d67702b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('client_approvals_client_id_fkey'), 'client_approvals', type_='foreignkey')
    op.create_foreign_key(None, 'client_approvals', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.drop_column('client_approvals', 'pin_hash')
    op.drop_column('client_approvals', 'password_hash')
    op.alter_column('clients', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('clients', 'pin_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'pin_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('clients', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('client_approvals', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('client_approvals', sa.Column('pin_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client_approvals', type_='foreignkey')
    op.create_foreign_key(op.f('client_approvals_client_id_fkey'), 'client_approvals', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
