"""some updates

Revision ID: 799745703a35
Revises: 01154f11651c
Create Date: 2026-01-15 13:59:07.527037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '799745703a35'
down_revision: Union[str, Sequence[str], None] = '01154f11651c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pos', ['phone'])
    op.alter_column('pos_user', 'role',
               existing_type=postgresql.ENUM('manager', 'cashier', 'storekeeper', name='pos_user_role_enum'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pos_user', 'role',
               existing_type=postgresql.ENUM('manager', 'cashier', 'storekeeper', name='pos_user_role_enum'),
               server_default=sa.text("'cashier'::pos_user_role_enum"),
               existing_nullable=False)
    op.drop_constraint(None, 'pos', type_='unique')
    # ### end Alembic commands ###
