"""Add error_message field

Revision ID: 861d2c2ede71
Revises: ef64514e9fc6
Create Date: 2026-01-14 18:24:32.617347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861d2c2ede71'
down_revision: Union[str, Sequence[str], None] = 'ef64514e9fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('client_approvals_client_id_fkey'), 'client_approvals', type_='foreignkey')
    op.create_foreign_key(None, 'client_approvals', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.drop_column('client_approvals', 'pin_hash')
    op.drop_column('client_approvals', 'password_hash')
    op.alter_column('clients', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('clients', 'pin_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('pos_user', sa.Column('require_password_change', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('users_employee_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_employee_id_fkey'), 'users', 'employees', ['employee_id'], ['id'])
    op.drop_column('pos_user', 'require_password_change')
    op.alter_column('clients', 'pin_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('clients', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('client_approvals', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('client_approvals', sa.Column('pin_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client_approvals', type_='foreignkey')
    op.create_foreign_key(op.f('client_approvals_client_id_fkey'), 'client_approvals', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
