"""pos section

Revision ID: a8c6ea4dca5a
Revises: e51985afc341
Create Date: 2026-01-14 10:37:11.773808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c6ea4dca5a'
down_revision: Union[str, Sequence[str], None] = 'e51985afc341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pos_user', sa.Column('require_password_change', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pos_user', 'require_password_change')
    # ### end Alembic commands ###
