"""some updates

Revision ID: ca6bd9ee0658
Revises: 861d2c2ede71
Create Date: 2026-01-15 11:22:39.147255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6bd9ee0658'
down_revision: Union[str, Sequence[str], None] = '861d2c2ede71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('pos', sa.Column('phone', sa.String(40), nullable=True))
    
    # Populate existing rows with a placeholder
    op.execute("UPDATE pos SET phone = '0000000000' WHERE phone IS NULL")
    
    # Alter the column to NOT NULL
    op.alter_column('pos', 'phone', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pos', type_='unique')
    op.drop_column('pos', 'phone')
    # ### end Alembic commands ###
