"""add require_password_change to pos_user

Revision ID: e51985afc341
Revises: ef64514e9fc6
Create Date: 2026-01-14 08:54:58.642774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51985afc341'
down_revision: Union[str, Sequence[str], None] = 'ef64514e9fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pos_user', sa.Column('require_password_change', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pos_user', 'require_password_change')
    # ### end Alembic commands ###
